### ISSUE TITLE
Getting Warnings in the console

### ISSUE THREAD

**Issue by Sivabilla** [aalavandhaann/blueprint-js#10]
Hi Aalavandhan,

I'm getting lots of warnings in the console regarding THREE.Loader andTHREE.WebGLRenderer, also in the demo link given in the project contains the same warnings!!!

Thanks,
Siva

**Comment by aalavandhaann** [comment]
Siva Kanna,

Can you post the warnings on your console? Please.

Regards,

#0K

**Comment by Sivabilla** [comment]
Hi Aalavandhaan,

These are the warnings from my browser console

Regards,
Siva



![console_error](https://user-images.githubusercontent.com/31128779/50198692-ab80a280-0372-11e9-8d68-d76fa102b52a.PNG)

**Comment by aalavandhaann** [comment]
Those warnings are part of the older type Json models loaded on the scene.
