### ISSUE TITLE
Error:'default' is not exported by node_modules\_es-enum@1.1.0@es6-enum\dist\enum.js

### ISSUE THREAD

**Issue by huhai0403** [aalavandhaann/blueprint-js#11]
**Describe the bug**
I get this error when I run 'rollup -c'.
![image](https://user-images.githubusercontent.com/14146688/50143424-81ce6980-02e7-11e9-9fc6-7fe9849be42c.png)

Thanks!!!

**Comment by aalavandhaann** [comment]
Are you sure the roll-up version is the latest one? Can you give now info on the node and roll-up version?

Regards,

#0K

**Comment by huhai0403** [comment]
> 你确定汇总版是最新版吗？您现在可以提供有关节点和汇总版本的信息吗？
> 
> 问候，
> 
> ＃0K

**Comment by huhai0403** [comment]
thank you very much！
![image](https://user-images.githubusercontent.com/14146688/50192264-7ffab980-036c-11e9-8e65-53c530e213a1.png)

**Comment by huhai0403** [comment]
I think it may be a problem with commenjs.

**Comment by aalavandhaann** [comment]
Is it fixed,?

**Comment by aalavandhaann** [comment]
I am not able to reproduce this issue. The original user can reopen this issue if they still have problems.
