### ISSUE TITLE
How to add the new item(roof) not celling  ?

### ISSUE THREAD

**Issue by AmarKothari** [aalavandhaann/blueprint-js#13]
Hi Srinivasan,
Your work looks amazing,
how will add the new roof(not celling which is present already) as an item,  please help me out.

Thanks & regards 
Amar kothari

**Comment by AmarKothari** [comment]
Hi Srinivasan,

Thank you so much for reply,
Actually i am using this existing project, so if you help me  to add one roof as a demo in this project then it is greatful for me . please help me out.

below i have attached the sample image.

 ![exterior](https://user-images.githubusercontent.com/29985615/50390931-840b4a80-0763-11e9-9c33-e91526b4f204.PNG)

Thanks & Regards,

Amar Kothari

**Comment by aalavandhaann** [comment]
The picture shows the view of exterior rather than the interior. I agree there will be plans to do the exterior but as of now there are tons of things to be completed for the interior. So this might have to wait.
