### ISSUE TITLE
total wall and floor area

### ISSUE THREAD

**Issue by micreales** [aalavandhaann/blueprint-js#14]
Hi, is there a function/module in this project where I can get the total floor area and total wall area of floorplan?
Thanks

**Comment by aalavandhaann** [comment]
Yes this is possible. In the models folder you have the necessary functions to achieve this

**Comment by micreales** [comment]
I tried to find but still no luck, what is the function there?

**Comment by aalavandhaann** [comment]
See https://github.com/aalavandhaann/blueprint-js/blob/master/src/scripts/model/floorplan.js

It has the function to get all the rooms. Here reach room is made of corners. Now the area of the room needs to calculated based on the polygon shape formed by the corners. 

Regards,

#0K

**Comment by micreales** [comment]
Wow thanks for this, it really helps. After getting the area of polygon
would that be the floor total? Im sorry im not familiar of getting area or
something, i just need on my task. Thanks

**Comment by micreales** [comment]
Hi , @aalavandhaann , I have a question, can I have the same way dragging or moving the floor items same the behaviour in wall items ?

**Comment by aalavandhaann** [comment]
Yes, anything that extends wallflooritem class will have this behavior. There should be items in the inventory to demonstrate this behavior

**Comment by micreales** [comment]
Hi, I tried to check the blueprint script, not sure how can I found the implementation of (when you drag or positioning the window or door) the wall becomes black, and the sensitivity is much smooth than positioning a rug.

**Comment by aalavandhaann** [comment]
Which script did you check? Check (link)[https://github.com/aalavandhaann/blueprint-js/tree/master/src/scripts/items]

**Comment by micreales** [comment]
Hi , do you have any idea on how can I retain the items even if I changes
the room size ?
(e.g the door is the corner left side, if I tried to adjust the floor plan
and increase the width of wall,
the door will still be there at the same place) ?

Thank you.

**Comment by micreales** [comment]
Hi, do you have any idea on rotating rug, (not allowed to penetrate or
stick agains the wall) ? Thanks
