### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by CanKavaloglu** [aalavandhaann/blueprint-js#16]
Hi #OK,

The code does not run on Internet Explorer since it is implemented in ES6 standards. I have made some changes in the code that I do not want to loose. Therefore, I have been searching for a way to compile the code from ES6 into ES5. 
I have been compiling the code with Babel but it does not seem to be working. It compiles the most of the code correctly but there are still some missing things. 

Is there a straightforward way to do it ? 

P.S: I have just found out about Babel so I am no pro about that.

Cheers

**Comment by aalavandhaann** [comment]
I am not sure about support for IE, this is one annoyance to get rid off. Maybe it is more of a philosophical question to support either coding standard or a browser standard. I believe there should be tricks out there to handle the conversion of ES6 to ES5 thus backward support. I haven't given it a thought much yet, but will update on this issue as and when dealing with it.

Regards,
#0K
