### ISSUE TITLE
adding new floor-plan 

### ISSUE THREAD

**Issue by yairabf** [aalavandhaann/blueprint-js#17]
Hi, First of all, thanks for your great project!
 
I'm Trying to load new floor-plan using the file app.js and changing the myHome variable to DWG file I converted to json.

When I'm trying doing so, I keep getting an error in the bp3djs.min.js in the function "var Model = function (_EventDispatcher)" (line 106111)

I guess the parsing in the library doesn't work well with the conversion.

I'm trying to find a way to take a DWG file and show it using the blueprint project.

Thanks a lot!

**Comment by aalavandhaann** [comment]
Hi,

I don't think any json file will work. JSON is only a standard of representing objects and values. For this to work you have to create the floorplan using blueprint-js and then download the json file. As of now I can tell you to save your dwg file as an image and use it as a carbon copy in the 2d view to reproduce the plan on blueprint-js. 

Regards,
#0K

**Comment by yairabf** [comment]
Hi,
Thanks for the quick response, 
Do you mean by saying a carbon copy that the blueprint-js will present it as an image?

Also, the variable myHome in app.js is a string (json) that represent the floor-plan.
If I'll find a way to convert the DWG file and represent it as a string would it work?

**Comment by aalavandhaann** [comment]
Did you try using the 2D floorplan interface of blueprint-js? In the top right expandable menu under "global"->"carbon sheet" you can import an image to use as reference for drawing your layout. Try it and let me know if you have any questions.

Regards, my#0K

**Comment by yairabf** [comment]
Hi,
Again, thank you very much for your elaborate response.
I want to make sure I understood you.
Did you mean to upload my DWG plan file as an image and then build my desirable plan using the blueprint-js on top of the image? 

I didn't succeded uploading the file using "global"->"carbon sheet->url".
In any case, my wish is to be able to take any plan and to present it using the blueprint-js tool.

In app.js
![Screen Shot 2019-03-14 at 11 43 55](https://user-images.githubusercontent.com/23613725/54346879-84263280-464e-11e9-94e5-462c32083472.png
It seems that the myHome var is a string that represents a floor plan and the 	"blueprint3d.model.loadSerialized(myhome);"
create the object to show in the blueprint-js editor.
Does the string is something you create or by the editor itself or if I would be able to create JSON string that represents a floor by external tools the function will know how to covert it? 

Thanks
