### ISSUE TITLE
Can't add some objects in 3D

### ISSUE THREAD

**Issue by GWillmann** [aalavandhaann/blueprint-js#19]
**Describe the bug**
When clicking on some 3D objects to add them to the scene, a error occurs and the object isn't added to the scene.

**To Reproduce**
Create a new layout
1. Go to 3D
2. Click on Toilet
3. Open developer console 
4. See error : `TypeError: "cached is undefined"`

**Expected behavior**
Object is added to the scene

**Screenshots**
<img width="1219" alt="Screenshot 2019-03-16 at 14 16 18" src="https://user-images.githubusercontent.com/5655900/54475824-672c6380-47f6-11e9-9a7f-bc7d3200d87e.png">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser firefox
 - Version 65.0.1

**Fix**
Simply adding `typeof cached !== 'undefined` fixes the problem and makes it possible to add the object to the scene. However being relatively new to this project, I don't know in which library it uses I should submit a PR.
There are many occurrences of the faulty line:
<img width="765" alt="Screenshot 2019-03-16 at 14 11 40" src="https://user-images.githubusercontent.com/5655900/54475847-bd99a200-47f6-11e9-99eb-b996c31de439.png">

Thanks for your work!

**Comment by aalavandhaann** [comment]
Many thanks for pointing this out GWilliam. I believe this error stems from the GLTFLoader module. Have a nice day ahead. 

Regards,
#0K

**Comment by aalavandhaann** [comment]
I believe this is coming from the @calvinscofield because the GLTFLoader is imported from there. Many thanks for this find. I need to fix it soon.

Regards,
#0K

**Comment by aalavandhaann** [comment]
This bug has been resolved with three-gltf-loader@l.105.0. Feel free to reopen this issue
