### ISSUE TITLE
save 2d model

### ISSUE THREAD

**Issue by moeinserpico** [aalavandhaann/blueprint-js#22]
how can save and  load 2d model in json or xml format?

**Comment by aalavandhaann** [comment]
Can you please elaborate? What do you mean by 2d model?

**Comment by moeinserpico** [comment]
simple floor plan
i want to design and save and load the model
can I?

**Comment by ravenwish1990** [comment]
In case you still need help (though, after 2 months, i doubt it), _bp3d_.**model.exportSerialized()** will export as JSON. If you only use the 2D floorplan(as I did), it will export everything related to the 3D view as empty objects.
Then, _bp3d_.**model.loadSerialized(** _yourJSONString_ **)** will load everything back, without issues.

Note: _bp3d = new BP3DJS.BlueprintJS( options )_

**Comment by moeinserpico** [comment]
Thanks for your consideration,
please elaborate more about options or refer me to corresponding link

**Comment by aalavandhaann** [comment]
I believe @ravenwish1990 has given the right directions on your original query. I am not sure what you mean by elaborate.
