### ISSUE TITLE
How do you do?

### ISSUE THREAD

**Issue by wencheng924** [aalavandhaann/blueprint-js#29]
I am Wencheng and very interesting in your project.
I installed your project on my laptop, analyzed details.
As you mentioned, there are many problems in this one.
I'm going to co-operate with you.
Let me know what do you say.
Thanks.

**Comment by aalavandhaann** [comment]
Hello WenCheng,

Firstly, my thanks to your kind words. I am happy to know you and about the possible collaboration we can have. Kindly reach me over email. ashok.srinivasan2002@gmail.com.

Regards,
#0K
