### ISSUE TITLE
Setting it up online?

### ISSUE THREAD

**Issue by tvsm22** [aalavandhaann/blueprint-js#3]
Hellow. I've stumbled upon on blueprint3d project about a year ago, liked the script, decided that it's too hard for me to figure out all the steps by myself.
A year passed, your version looks really cool, the problem is still the same :-)
Wanted to know if you can help me to set up the script and make a tutorial on how to export 3d models from sketchup and import it to blueprint3d
Thanks.

**Comment by aalavandhaann** [comment]
Hello thank you for the compliments. There are two things in your question

* How to set this up?
- You should know how you install and use NPM. If that is done then the README tells you how to setup this library. 

* How to export 3d models from sketchup and import it to blueprint3d?
- please refer to the wiki section on how to do this. I have written a brief tutorial to import GLTF models as an inventory into blueprint-js. I believe SketchUp can export GLTF models. If you are lost then kindly refer to this [url](https://extensions.sketchup.com/en/content/gltf-exporter).

Let me know specifically if you encounter any issues in your adventure. Would be more than glad to lend you a hand. Cheers. 

Regards,

#0K

**Comment by tvsm22** [comment]
I meant, maybe there is a person who can help and get paid for doing that )
