### ISSUE TITLE
index2.html no visible

### ISSUE THREAD

**Issue by sagirr** [aalavandhaann/blueprint-js#30]
Hello, 
Aalavaandhaan thanks for your project,
I install  index2.html  script but when open this upload in screen but this is invisible , 
Three is a solution for this problem,

**Comment by aalavandhaann** [comment]
Sorry, you are not being clear. Can you please be more descriptive about the issue you are facing?

Regards,
#0K

**Comment by sagirr** [comment]
I'm sorry, my English is not very good.
When you run the link, you can see the error,

https://aalavandhaann.github.io/blueprint-js/build/index2.html

I installed it, but the plan doesn't appear on the screen

**Comment by aalavandhaann** [comment]
Hi,

They index2.html is not valid. Don't use the index2.html file. Use
index.html
