### ISSUE TITLE
Question regarding object position

### ISSUE THREAD

**Issue by Ozanaydinn** [aalavandhaann/blueprint-js#31]
Hello,
I'm trying to get object coordinates with respect to the bottom left corner of the room-so that the coordinates of the bottom left corner will always be 0-0-0-, provided that the room will always be a rectangle. Is there any way to do this?
Thanks!

**Comment by aalavandhaann** [comment]
For the room you always see the account at the origin. It's a set of small rgb lines at the axis. For the bottom left corner it can be done using the bounds mechanism. You would consider the minx, Maxy, values

**Comment by Ozanaydinn** [comment]
Hey, thank you for the quick reply!
I have a completely different question to ask, should I open a new issue or can I bother you from someplace else? :)

**Comment by aalavandhaann** [comment]
If it's a issue related to the blueprint-js framework and it's different then kindly open a new issue. If it's something related to how something needs to be done in 3D generally then please stick to forums, stackoverflow or email me at ashok.srinivasan2002@gmail.com

Regards,

#0K

**Comment by aalavandhaann** [comment]
Closing this issue as there is no further discussion happening.
