### ISSUE TITLE
How to bypass wall creation process to create outdoor walls

### ISSUE THREAD

**Issue by CanKavaloglu** [aalavandhaann/blueprint-js#32]
Hi #OK,

I was wondering how can I force the code to create an outdoor wall not an interior one. The outdoor ones has an white edge on the top and they seem thicker and they only have back-side edge. 

I would like to have the same type inside of the property. How should I change the code for that ?

Thanks !

**Comment by aalavandhaann** [comment]
It's inside edge.js of three module. Look into the method ```updatePlanes()```
