### ISSUE TITLE
How to scale the floor plan ?

### ISSUE THREAD

**Issue by CanKavaloglu** [aalavandhaann/blueprint-js#4]
I have some floor plans that belong to real properties. What I want to do is scale the floor plan according to the real floor plan so that the final model would be consistent with the property size. 

To this end, I could not find where the length of the walls (in the floor plan) are is computed. I suppose it is a simple subtraction between two 2d vectors. When subtract the "start" and "end" corner points in newWall method, it gives me the non-rounded lengths of the walls. However, I could not find where this very same computation is done in the code (whether it is in Walls or Corners) ?

Please check the image given below, it is an example of the case that I tried to describe above.

![oie_p7zyvg7kvmhn](https://user-images.githubusercontent.com/13483369/48840851-151b8a00-ed90-11e8-8218-6380f62df1f0.png)

Here, as you can see at the right bottom corner there is the scale of the floor plan which indicates how long are the walls of the property in the floor plan. 

So my idea is to put this image as a background of "floorplanner" div. Then, I will basically draw on the scale line (at the bottom) starting from 0 to 5m. Then I will consider this line (wall) as 5 meters. Finally, I will draw the walls (going over the background image like a carbon paper). What I expect is to have the model (3d) in the proper scale of the property. 

Any suggestions how can I scale the distances between corners or/and walls ? 

Thanks in advance.

**Comment by aalavandhaann** [comment]
You have different units on the top right that says "open controls". Here you can change to different units. To do a carbon copy, don't you think it's wise to convert the existing plans with imaging or vision techniques?  Even then your idea of carbon copy is a good feature to add. So the idea will be that a user should upload his own floorplan and start drawing on top of it. This is difficult to be demonstrated on the GitHub hosted url but let me see if this can be done on my private hosting server.

Regards,

#0K

**Comment by aalavandhaann** [comment]
Or perhaps the image of the floorplan could come from a user supplied url. Do you think that would be a good idea?

Regards,

#0K

**Comment by aalavandhaann** [comment]
I completely understand this. It's only that I am wondering how to add this functionality from an user point of view. Once you apply the image it will be having a dimension according to the floorplan framework. That can be either too small or too big. So using the idea of bottom right scaling line reference is pretty smart. But I am afraid if you let the user click on a pixel and draw a line ending at another pixel it can only be approximately scaled but not accurately scaled. Fine, I will try to implement a crude version first. We need to begin somewhere first. But this idea of yours is really valuable. Thanks for that. 

If you don't mind can you please share your implementation url? It would be a lot motivating to see this being used elsewhere. But no obligations so don't worry.

Regards,

#0K

**Comment by CanKavaloglu** [comment]
Thank you for your compliment. I see your point, but it does not strictly have to be precise for the first version of this idea you know ? This is just a beginning of it. For the url of my implementation, I am currently working on local but I will gladly share it here when the things are a bit tidier. So lets keep in touch on this issue !

Lastly, in which part of the code the calculation  between two corners of the wall is done and the distance is computed. Also, where is this distance attached to the canvas ? 

Cheers !

**Comment by CanKavaloglu** [comment]
> Thank you for your compliment. I see your point, but it does not strictly have to be precise for the first version of this idea you know ? This is just a beginning of it. For the url of my implementation, I am currently working on local but I will gladly share it here when the things are a bit tidier. So lets keep in touch on this issue !
> 
> Lastly, in which part of the code the calculation between two corners of the wall is done and the distance is computed. Also, where is this distance attached to the canvas ?
> 
> Cheers !

**Comment by aalavandhaann** [comment]
The values of pixel per centimeters and vice versa for the floorplan 2d drawings are in the class Floorplaner inside the floorplan module. [Link] (https://github.com/aalavandhaann/blueprint-js/blob/master/src/scripts/floorplanner/floorplanner.js)

**Comment by aalavandhaann** [comment]
Hey CanKavaloglu,

I have added a carbonsheet class to the floorplanner module. Also the ui has been updated in the demo to reflect this. This can been seen as a suboption in the global options of the dat.gui. supply the url field with an image location. See if this helps you.

Regards,

#0K

**Comment by CanKavaloglu** [comment]
Thanks for the effort ! But I do not see how it really scales to get 5 meters in that example given above. How should I provide the information that this line is 5 meters, so scale accordingly, you know ? If it works based on a different perspective, can you enlighten me on how it is supposed work / what is the behavior sequence of the process after I provide  an URL to the Carbon Sheet class ? 

Cheers !

**Comment by aalavandhaann** [comment]
The idea is after you load the image from the url it will have a width and height according to the floorplan units. You can set the real width and real height of the image to match the dimensions of the floorplan. Move x and move y is to move the image on the floor plan canvas. Anchor x and anchor y is the location from which the image will be scaled. Follow the below steps to setup the carbon sheet

* Load an image from the url
* Position the image on the canvas using move x and move y
* Draw a floorplan wall on the image that matches 5 meters overlapping the image 5 meters
* Set the anchor point (red Dot) to the beginning of the 5 metre line
* Now set the real width and real height to match the image

The above process should scale the image according to the floorplan system

Regards,

#0K
