### ISSUE TITLE
First person

### ISSUE THREAD

**Issue by sagirr** [aalavandhaann/blueprint-js#42]
Hello .

How can we use first-person on the phone.
Is there a solution ?

Thanks..

**Comment by aalavandhaann** [comment]
Hi,

Export your scene as gltf. This option is available in the top right corner of the 3d editor screen.  Once you have exported then look into this [link](https://github.com/aalavandhaann/blueprint-js/tree/master/build/vrtest) for an example of how to use your exported gltf model in a vr scene or view as first person using a-frame controls

![Selection_091](https://user-images.githubusercontent.com/8164567/71708438-5cf84780-2dbf-11ea-80cc-b8c05183cd0b.png)


Regards,
#0K
