### ISSUE TITLE
add function gltf exporter

### ISSUE THREAD

**Issue by AWAIS97** [aalavandhaann/blueprint-js#54]
I used blueprint3d.js and i want to add glft exporter function.When include this function in example.js file  and  i get some error in my console like GLTFExporter is not define.Can you help me with that

```
//gltf exporter
  function SaveDesign() {
    var data = blueprint3d.model.exportSerialized();
    var exporter = new GLTFExporter();
    exporter.parse(data, function (result) {
      var output = JSON.stringify(result, null, 2);
      console.log(output);
      downloadJSON(output, "scene.gltf");
    });
  }
```

Thanks

**Comment by aalavandhaann** [comment]
Change GltfExporter to THREE.GltfExporter. This is not the place for queries on threejs API.

**Comment by AWAIS97** [comment]
Okay I apologize for that.
I tried this THREE.GltfExporter but this is also said THREE is not define
need help

**Comment by aalavandhaann** [comment]
Did you include threejs in the html script tag?

**Comment by AWAIS97** [comment]
Now its give THREE.GLFTExporter is not a constructor

**Comment by AWAIS97** [comment]
When i include a script tag of GLFTExporter.js in html then
"THREE.GLFTExporter is not a constructor " is gone but one more thing is
occur that is

Uncaught (in promise) ReferenceError: downloadJSON is not defined
    at example.js:546
    at GLTFExporter.js:2082

**Comment by AWAIS97** [comment]
When i include a script tag of GLFTExporter.js in html then
"THREE.GLFTExporter is not a constructor " is gone but one more thing is
occur that is

Uncaught (in promise) ReferenceError: downloadJSON is not defined
    at example.js:546
    at GLTFExporter.js:2082

please help me with that
