### ISSUE TITLE
code not found

### ISSUE THREAD

**Issue by AWAIS97** [aalavandhaann/blueprint-js#57]
Where is the code of EVENT_GLTF_READY module?

I only see in events.js file 
export const EVENT_GLTF_READY = 'GLTF_READY_EVENT';

**Comment by aalavandhaann** [comment]
Awais,

Looks like you are missing the basics of using es6. So I would request you
to get yourself acquainted with it first. Because your question is not
valid as EVENT_GLTF_READY is not a module but a constant member of the
blueprint-js framework. Good luck.

Regards,
#0K

**Comment by AWAIS97** [comment]
I mean What its functionality?
I am getting error addEventListener is not a function
 blueprint3d.three.addEventListener(saveGLTFCallback);
