### ISSUE TITLE
Integrating with React

### ISSUE THREAD

**Issue by thomaz-yuji** [aalavandhaann/blueprint-js#58]
Hello,

any glues on implementing this with React?
I would like to draw walls based on a json with x and y values.

**Comment by aalavandhaann** [comment]
Unfortunately, I don't have any experience with react. I bet you can integrate this framework as long as it supports es6 js

**Comment by technbuzz** [comment]
> Hello,
> 
> any glues on implementing this with React?
> I would like to draw walls based on a json with x and y values.

I have implemented it in the vue, I think it would be somewhat similar in react as well. Move the code in `document.ready` function of jQuery in `app.js` to the mounted lifecycle hook of the component. Rest are the regular methods that can be placed anywhere, they can be modularized.

**Comment by zhongweijian-svg** [comment]
All about how you solved Geometry and Face obsolescence？
