### ISSUE TITLE
export plan feature request

### ISSUE THREAD

**Issue by robbisy** [aalavandhaann/blueprint-js#6]
**Is your feature request related to a problem? Please describe.**

I would like to have my floor plan on my website

**Describe the solution you'd like**

I would like to create my floorplan with blueprint-js and then export it on my website

**Describe alternatives you've considered**

Maybe the possibility to export a pdf file of the floorplan created

**Comment by aalavandhaann** [comment]
Have you cloned this repository on your web host? Did you setup the roll-up to compile js?

**Comment by robbisy** [comment]
No I didn't when I say I would like to have my floor plan on my website I mean just the 3d canvas.
The idea is to build the house plan on https://aalavandhaann.github.io/blueprint-js/build/ and then to export the 3d model on my website 
I don't know if It's possible 
Do you think it is ?
