### ISSUE TITLE
Clean wall joins

### ISSUE THREAD

**Issue by technbuzz** [aalavandhaann/blueprint-js#64]
**Describe the bug**
I have modified the original project based on my needs. When we change the thickness then the wall edges are not clean as you can see in the image below. The room area is also not properly created. There is an empty space.

![image](https://user-images.githubusercontent.com/1523391/99178468-cb6e9b80-272c-11eb-9544-c24c41c5806f.png)

**To Reproduce**
We need to modify the wall styles in order to properly see the difference
1. Go to WallView2d.js
2. Comment this line 
```javascript
  update () {
      // this.__drawDimensionLine()
      this.__updateDimensionText()
  }
```
3. Update the following function as 
```javascript
__drawPolygon(color = 0xDDDDDD, alpha = 1.0) {
        let points = this.__getPolygonCoordinates();
        this.clear();
        // this.beginFill(color, alpha);
        this.beginFill(color, 0.05); //
        for (let i = 0; i < points.length; i++) {
            let pt = points[i];
            if (i === 0) {
                this.moveTo(pt.x, pt.y);
            } else {
                this.lineTo(pt.x, pt.y);
            }
        }
        this.endFill();

        // let cornerLine = this.__getCornerCoordinates();
        // this.lineStyle(Dimensioning.cmToPixel(this.__wall.thickness), color, alpha, 0.5);
        // this.moveTo(cornerLine[0].x, cornerLine[0].y);
        // this.lineTo(cornerLine[1].x, cornerLine[1].y);

        // this.lineStyle(1, 0xFFFFFF);
        // this.moveTo(cornerLine[0].x, cornerLine[0].y);
        // this.lineTo(cornerLine[1].x, cornerLine[1].y);
    }
```
4. See the effect

**Expected behavior**

Something like the following would be nice. Here the corner angle is proper. You can try it on this website https://www.wanaplan.com/try_plan

![image (1)](https://user-images.githubusercontent.com/1523391/99178477-e50fe300-272c-11eb-9b2d-bd2b0e1a7c2d.png)

**Comment by aalavandhaann** [comment]
Dear Samiullah Khan,

Many apologies for the delay in the reply. Writing my thesis and other consulting jobs were keeping me really busy. ATM I am afraid that time is needed to achieve this goal. Indeed your link is useful and is the right way to render them. If you can manage to implement this then feel free to do a PR and I would gladly integrate them. I guess to solve this problem you should look into the interiorStart(), interiorEnd(), exteriorStart(), exteriorEnd() methods in the half_edge.js inside the model folder. 

Regards,
#0K

**Comment by aalavandhaann** [comment]
This is done now. Closing the issue

Regards,
#0K
