### ISSUE TITLE
take the stair and possibilty of collision detection

### ISSUE THREAD

**Issue by robbisy** [aalavandhaann/blueprint-js#8]
Hi 
Thanks for this great work. I have a request that I think can make this project even greater.

**Is your feature request related to a problem? Please describe.**

 I'm always frustrated when I'm passing through wall , object or stair

**Describe the solution you'd like**

The possibility to add collision detection on wall or object and have the possibiliy to take the stair

**Additional context**

https://www.babylonjs.com/demos/espilit/
A demo with babylon.js when there is collision detection and you can take the stair

**Comment by aalavandhaann** [comment]
Robbisy,

Firstly, you have to understand that this is not a game engine but a simple Floorplaner framework in progress. Collision detection is more for game maps. Maybe in the future there will be plans to include multiple floors and stairs climbing. 

Regards,
#0K
