### ISSUE TITLE
How to resize Wall

### ISSUE THREAD

**Issue by Sivabilla** [aalavandhaann/blueprint-js#9]
Hi Aalavandhaann,

Thanks for Customizing blueprint3d to a fantastic project(Semma Project Thalaiva),i just want to know how to resize the wall interms of height,width and thickness these properties are present inbuild for items but i want for wall,please help me out

Thanks & Regards,
Siva

**Comment by aalavandhaann** [comment]
Hello Shiva Kanna,

Firstly, sorry for the late and delayed  reply. Was busy with my thesis work. As of now the width of walls are constant. Today is something to do in the near future. I am right now busy with the thesis work of mine. If you are able to change this feature aspect then I will be glad to integrate your pull request. Let me know if you have any issues. 

BTW thank you very much for your complements. You can always reach me at my email for any assistance. 

Regards,

#0K

**Comment by aalavandhaann** [comment]
As I said earlier the changing of wall height and thickness is constant for all of them. I guess by dynamically you mean having a different values for thickness and height of every wall. I see the point of varying thickness for walls but I believe the height needs to remain the same for all the walls in a floor. To have a thickness look into the Json file format and add the relevant property. Also the code has to be implemented to parse this new information in the Json. 
Regards,
#0K

**Comment by Sivabilla** [comment]
ok thalaiva, let the wall be constant, is there any possibilities of adding the roof i have created an object in blender, now how to fix it as a roof or any existing object to place over the wall like roof.

Thanks & Regards,
Siva

**Comment by aalavandhaann** [comment]
I think it's already there kanna. The ceiling is not visible in the 3D editor mode. Export the scene as gltf and you will see it.

Regards,

#0K

**Comment by CanKavaloglu** [comment]
Hi all,

I also have the same problem with the ceiling. Well, I am using different kinds of lights in the model and because of the ceiling the light is not getting through. How can I disable the creation of the ceiling on the creation of the room ?

Thanks

**Comment by aalavandhaann** [comment]
Hi,

The ceiling can be disabled in the code @ https://github.com/aalavandhaann/blueprint-js/blob/master/src/scripts/three/floor.js

There method buildRoof takes care of building a roof. Can you try to put the lights under the ceiling inside the room instead of removing? The ceiling is useful with first person or VR walkthrough.

Regards,

#0K

**Comment by Sivabilla** [comment]
> I think it's already there kanna. The ceiling is not visible in the 3D editor mode. Export the scene as gltf and you will see it.
> 
> Regards,
> 
> #0K

thank u thalaiva, i will check this out, is there any method to make the ceiling visible in 3d editor mode itself.
Thanks&Regards,
Siva

**Comment by CanKavaloglu** [comment]
> Hi,
> 
> The ceiling can be disabled in the code @ https://github.com/aalavandhaann/blueprint-js/blob/master/src/scripts/three/floor.js
> 
> There method buildRoof takes care of building a roof. Can you try to put the lights under the ceiling inside the room instead of removing? The ceiling is useful with first person or VR walkthrough.
> 
> Regards,
> 
> #0K

Yeah I have already tried it and when the light is under the ceiling, the model gets the light. I am aware that the ceiling is useful in FPV mode but I need the light source a bit far from the model. Well, I will try both versions and let you also know which one works better in the sense of the lights and shadows.

Cheers !

**Comment by CanKavaloglu** [comment]
I have just tried both versions and the ceilings are quite useful as you mentioned. Therefore, is there any way that these ceilings can be implemented with another type of material so that they transmit the light through ? If you know such a way, could you please point me to that direction ? 

Cheers!

**Comment by aalavandhaann** [comment]
"Transmitting the light through" - I looked into the examples and found out that the volumetric lights are done using custom shaders. In this case one needs to have the ability of customizing the material of an item (not textures). I am not sure how this can be achieved. Any ideas? Do you think the user should be able to to manipulate materials? I am not sure if an interior designer will be aware of such ideas. Let me know your views.

Regards,

#0K
